### ISSUE TITLE
BUG AFTER BAN

### ISSUE THREAD

**Issue by ulduar1** [kepo123/AcolytesWoW#1]
My pala was banned for 1 month. 24th march was the last day of my ban. now its 27th march and my pala is still banned. when i try to connect it disconects me instantly. in the site of acolytes it says that the account status is still banned.

**Comment by kepo123** [comment]
Give us more information like username, email and reason. You can send the information to: donate-acolytes@mail.bg with subject "GitHub - Unban - problem".

**Comment by ulduar1** [comment]
I send the information to donate-acolytes@mail.bg

**Comment by ulduar1** [comment]
Username: stormwind
Reason for ban: Donor in wsg
Account was banned on: 22.02.2017
Account unban date was on: 24.03.2017, 21:03h
I waited till the unban date and when i tryed to log in it discconected me instantly. 4 days after the unban date its still disconecting me when i try to connect. In  your site (acolytesrealm.com) in "account status" section account is "banned"

**Comment by kepo123** [comment]
After verification we found that:
- there is a bug in the system ban

We Apologise for the inconvenience. Account is enabled! We will try to solve the problem as soon as possible!
