### ISSUE TITLE
The player "Andre" use Hacker of Fly in WGS battle.

### ISSUE THREAD

**Issue by ProSlayerFury** [kepo123/AcolytesWoW#4]
# The flag trail indicates how it rises from the ground by flying with the hack.

On the map you can see how it goes to a place where no one can reach it to attack it. (Flag Aly)
![andre hack of fly in wgs 1](https://cloud.githubusercontent.com/assets/26825426/24571531/700fb31e-1637-11e7-8de6-c17f7a97019c.jpg)
![andre hack of fly in wgs 2](https://cloud.githubusercontent.com/assets/26825426/24571538/796405be-1637-11e7-9cdb-c6597dbc7a1f.jpg)

**Comment by kepo123** [comment]
Banned.
