### ISSUE TITLE
Stolen Acc

### ISSUE THREAD

**Issue by stormwindshit** [kepo123/AcolytesWoW#9]
So unfortunately my account was stolen. I think it's because my password was the nickname of my e-mail. I think so because once I logged and asked the stealer how he got it and he said "by luck". A week or so after this I tried to log in but the password was changed. I texted one of the GMs (who is from my country) in Facebook because I didn't seem to find Acolyte's Stuff e-mail in site. He just "seen". Some days after that I tried again but the same happened. How can someone change the password of my account? Without having my e-mail address. <I think you should have the e-mail who created the account to donate to it.> 
Hope somebody more moderate checks this out and actually help me.

**Comment by kepo123** [comment]
Character name?

**Comment by stormwindshit** [comment]
Akatsiya

2017-04-19 13:35 GMT+03:00 kepo123 <notifications@github.com>:

**Comment by kepo123** [comment]
A new password has been sent to the account email.

**Comment by kepo123** [comment]
Banned due to sale.

**Comment by stormwindshit** [comment]
I didn't sell it. Oh my fucking god. Yesterday some guy "Blind" (Who
appeared to be the one who stole Akatsiya) said that he will get his
character back or I will be banned. SO YOU BELIEVE HIM? WHY THE FUCK YOU DO
ALL THIS SHIT TO YOUR DONATORS?????????? PEOPLE DONATE AND THEN YOU DON'T
FUCKING CARE. YOU KNOW WHAT A DONATOR IS? SICK OF YOUR SHIT..

2017-04-23 12:11 GMT+03:00 kepo123 <notifications@github.com>:
